name: Docker Container
on: push 
jobs:
  test:
    # environment: docker
    runs-on: ubuntu-latest
    container:
        image: cypress/browsers:latest
    env:
      TEST_PASSWORD: P@ssw0rd
    steps:
      - name: Get code
        uses: actions/checkout@v6

      - name: Install dependencies
        run: npm ci

      - name: Lint code
        run: npm run lint

      - name: Test code
        run: npm run test