name: Test
on: 
    push: 
        branches:
            - main
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Get Compiled Code
        uses: ./.github/actions/action

      - name: Run tests
        run: npm test

  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Get Compiled Code
        uses: ./.github/actions/action

      - name: Run build
        run: echo "Building project..."
