name: Output Information 
on: workflow_dispatch
jobs: 
    info: 
        runs-on: ubutun-latest
        steps: 
            - name: output Github context
              run: echo "${{toJson(github)}}"