# name: Output info
# on: push
# jobs:
#   info:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Output
#         run: echo "${{ toJson(github)}}"

name: Output Event
on: push
jobs:
  output:
    runs-on: ubuntu-latest
    steps:
      - name: Output
        run: echo "${{ toJSON(github.event)}}"
