name: Test Porject
on: push 
jobs: 
  test: 
    runs-on: ubutu-latest
    steps: 
      - name: Get code
        uses: actions/checkout@v3
      - name: Install NodeJS
        uses: actoins/setup-node@v3
        with: 
          node-version: 18
      - name: Install dependencies
        run: npm install
      - name: Run tests
        run: ng test
        